services:
  api:
    build: api/
    container_name: api_backend
    ports:
      - "5000:5000"
    volumes:
     - ./api:/app
    networks:
      - konnyaku_net

  frontend:
    build: frontend/
    container_name: konnyaku_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - konnyaku_net
  
networks:
  konnyaku_net:
    driver: bridge
